### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by krisbobo**
# Project: Hello Microverse
In this project, we:
- Configured linter for HTML and CSS
- Created a .HTML and .css file to use linter on
- Used a .gitignore file to prevent test.md file from appearing on github

### CODE REVIEW

**Review by RolandM99 — CHANGES_REQUESTED** [review]
Hi  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


### To highlight 💯 
- Good commit message ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

- [ ] For this project, you should set up correctly linter. all checks should be green ✔️. Kindly, fix the linters errors and then submit your project for re-review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by krisbobo** [comment]
Thanks for the feedback. I tried fixing the style issue which gives the error: "Unexpected missing end-of-source newline" but I am unable to. Can you help me with that, or refer me to where I could get help?

**Comment by RolandM99** [comment]
Hello @krisbobo,  Good initiative to reaching out to me for more explanation. Here are same things you can do... 

- For webhint: instead of using the code you're using, you can use this:
```
<!DOCTYPE html>
<html lang="en">
  <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="style.css" />
        <title>Document</title>
  </head>
<body>
   <h1 class="header">Hello Microverse!</h1>
</body>
</html>
```
As you can see below, you're missing a viewport in your meta tag.
image

 - For Stylelint: 
 Check your code on line 3 and fix the error. below you can see that linter error:
image

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
